[project]
name = "pii-extractor"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "gliner>=0.2.24",
    "protobuf>=6.33.4",
    "torch>=2.10.0",
    "transformers>=4.57.6",
]
